CREATE TABLE IF NOT EXISTS Users (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Username NVARCHAR(256) NOT NULL,
    Forename NVARCHAR(256) NOT NULL,
    Surname  NVARCHAR(256) NOT NULL,
    EmailAddress NVARCHAR(256),
    DOB DATE,
    AddressId INT,
    PrimaryEventRoleId INT
);

CREATE TABLE IF NOT EXISTS EventRoles (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL,
    Description NVARCHAR(1024),
    RowStatus INT NOT NULL DEFAULT 0
);